export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '@styles/global.css'
import '@Components/Nav'
import Nav from '@Components/Nav'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='main'>
          <div className='gradient' />
        </div>
        <main className='app'>
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}
